branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
global:
  application_name: flask-test2
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
